// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

import type { Client, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
  ApplyTieringPartitionData,
  ApplyTieringPartitionErrors,
  ApplyTieringPartitionResponses,
  GetHealthData,
  GetHealthErrors,
  GetHealthResponses,
  GetTableData,
  GetTableErrors,
  GetTableResponses,
  GetTieringHistoryData,
  GetTieringHistoryErrors,
  GetTieringHistoryResponses,
  GetTieringPlanData,
  GetTieringPlanErrors,
  GetTieringPlanResponses,
  GetTieringStatusData,
  GetTieringStatusErrors,
  GetTieringStatusResponses,
  ListConditionsData,
  ListConditionsErrors,
  ListConditionsResponses,
  ListDetachedPartsData,
  ListDetachedPartsErrors,
  ListDetachedPartsResponses,
  ListMutationsData,
  ListMutationsErrors,
  ListMutationsResponses,
  ListNodesData,
  ListNodesErrors,
  ListNodesResponses,
  ListOperationsData,
  ListOperationsErrors,
  ListOperationsResponses,
  ListPartEventsData,
  ListPartEventsErrors,
  ListPartEventsResponses,
  ListReplicationQueueData,
  ListReplicationQueueErrors,
  ListReplicationQueueResponses,
  ListStorageDisksData,
  ListStorageDisksErrors,
  ListStorageDisksResponses,
  ListTableColumnsData,
  ListTableColumnsErrors,
  ListTableColumnsResponses,
  ListTablePartitionsData,
  ListTablePartitionsErrors,
  ListTablePartitionsResponses,
  ListTablePartsData,
  ListTablePartsErrors,
  ListTablePartsResponses,
  ListTablesData,
  ListTablesErrors,
  ListTablesResponses,
  PauseTieringData,
  PauseTieringErrors,
  PauseTieringResponses,
  ResumeTieringData,
  ResumeTieringErrors,
  ResumeTieringResponses,
  RetryTieringPartitionData,
  RetryTieringPartitionErrors,
  RetryTieringPartitionResponses,
} from './types.gen';
import {
  zApplyTieringPartitionBody,
  zApplyTieringPartitionPath,
  zApplyTieringPartitionQuery,
  zApplyTieringPartitionResponse,
  zGetHealthResponse,
  zGetTablePath,
  zGetTableResponse,
  zGetTieringHistoryQuery,
  zGetTieringHistoryResponse,
  zGetTieringPlanQuery,
  zGetTieringPlanResponse,
  zGetTieringStatusResponse,
  zListConditionsQuery,
  zListConditionsResponse,
  zListDetachedPartsPath,
  zListDetachedPartsQuery,
  zListDetachedPartsResponse,
  zListMutationsQuery,
  zListMutationsResponse,
  zListNodesQuery,
  zListNodesResponse,
  zListOperationsQuery,
  zListOperationsResponse,
  zListPartEventsQuery,
  zListPartEventsResponse,
  zListReplicationQueueQuery,
  zListReplicationQueueResponse,
  zListStorageDisksQuery,
  zListStorageDisksResponse,
  zListTableColumnsPath,
  zListTableColumnsQuery,
  zListTableColumnsResponse,
  zListTablePartitionsPath,
  zListTablePartitionsQuery,
  zListTablePartitionsResponse,
  zListTablePartsPath,
  zListTablePartsQuery,
  zListTablePartsResponse,
  zListTablesQuery,
  zListTablesResponse,
  zPauseTieringResponse,
  zResumeTieringResponse,
  zRetryTieringPartitionBody,
  zRetryTieringPartitionPath,
  zRetryTieringPartitionQuery,
  zRetryTieringPartitionResponse,
} from './zod.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Liveness probe
 *
 * Returns the current service status.
 */
export const getHealth = <ThrowOnError extends boolean = false>(
  options?: Options<GetHealthData, ThrowOnError>
): RequestResult<GetHealthResponses, GetHealthErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(z.never()),
        })
        .parseAsync(data),
    responseValidator: async data => await zGetHealthResponse.parseAsync(data),
    url: '/healthz',
    ...options,
  });

/**
 * List configured nodes
 *
 * Returns configured ClickHouse nodes plus request-time reachability and
 * coarse replication health. This endpoint is intentionally unpaginated:
 * the collection is bounded by the configured node list.
 *
 */
export const listNodes = <ThrowOnError extends boolean = false>(
  options?: Options<ListNodesData, ThrowOnError>
): RequestResult<ListNodesResponses, ListNodesErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListNodesResponses, ListNodesErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(zListNodesQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListNodesResponse.parseAsync(data),
    url: '/nodes',
    ...options,
  });

/**
 * List disks
 *
 * Returns disk inventory across configured nodes. Unknown or unbounded
 * remote capacity is represented with capacityKnown=false and null capacity
 * fields rather than ClickHouse sentinel values.
 *
 */
export const listStorageDisks = <ThrowOnError extends boolean = false>(
  options?: Options<ListStorageDisksData, ThrowOnError>
): RequestResult<ListStorageDisksResponses, ListStorageDisksErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListStorageDisksResponses, ListStorageDisksErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(zListStorageDisksQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListStorageDisksResponse.parseAsync(data),
    url: '/storage/disks',
    ...options,
  });

/**
 * List watched tables
 *
 * Returns table inventory normalized across configured nodes. Missing
 * database or table query filters produce an empty result set, not 404.
 *
 */
export const listTables = <ThrowOnError extends boolean = false>(
  options?: Options<ListTablesData, ThrowOnError>
): RequestResult<ListTablesResponses, ListTablesErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListTablesResponses, ListTablesErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(zListTablesQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListTablesResponse.parseAsync(data),
    url: '/tables',
    ...options,
  });

/**
 * Get table detail
 *
 * Returns detailed table state, including per-node table metadata.
 */
export const getTable = <ThrowOnError extends boolean = false>(
  options: Options<GetTableData, ThrowOnError>
): RequestResult<GetTableResponses, GetTableErrors, ThrowOnError> =>
  (options.client ?? client).get<GetTableResponses, GetTableErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: zGetTablePath,
          query: z.optional(z.never()),
        })
        .parseAsync(data),
    responseValidator: async data => await zGetTableResponse.parseAsync(data),
    url: '/tables/{database}/{table}',
    ...options,
  });

/**
 * List table columns
 *
 * Returns schema detail per node because schema drift can occur during failed or partial DDL.
 */
export const listTableColumns = <ThrowOnError extends boolean = false>(
  options: Options<ListTableColumnsData, ThrowOnError>
): RequestResult<ListTableColumnsResponses, ListTableColumnsErrors, ThrowOnError> =>
  (options.client ?? client).get<ListTableColumnsResponses, ListTableColumnsErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: zListTableColumnsPath,
          query: z.optional(zListTableColumnsQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListTableColumnsResponse.parseAsync(data),
    url: '/tables/{database}/{table}/columns',
    ...options,
  });

/**
 * List table partitions
 *
 * Returns logical partition placement and active operation overlays. The
 * partitionId field is ClickHouse system.parts.partition_id verbatim and
 * is unique only within the database/table pair.
 *
 */
export const listTablePartitions = <ThrowOnError extends boolean = false>(
  options: Options<ListTablePartitionsData, ThrowOnError>
): RequestResult<ListTablePartitionsResponses, ListTablePartitionsErrors, ThrowOnError> =>
  (options.client ?? client).get<ListTablePartitionsResponses, ListTablePartitionsErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: zListTablePartitionsPath,
          query: z.optional(zListTablePartitionsQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListTablePartitionsResponse.parseAsync(data),
    url: '/tables/{database}/{table}/partitions',
    ...options,
  });

/**
 * List active parts
 *
 * Returns physical parts from system.parts, per node.
 */
export const listTableParts = <ThrowOnError extends boolean = false>(
  options: Options<ListTablePartsData, ThrowOnError>
): RequestResult<ListTablePartsResponses, ListTablePartsErrors, ThrowOnError> =>
  (options.client ?? client).get<ListTablePartsResponses, ListTablePartsErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: zListTablePartsPath,
          query: z.optional(zListTablePartsQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListTablePartsResponse.parseAsync(data),
    url: '/tables/{database}/{table}/parts',
    ...options,
  });

/**
 * List detached parts
 *
 * Returns detached parts from system.detached_parts, per node.
 */
export const listDetachedParts = <ThrowOnError extends boolean = false>(
  options: Options<ListDetachedPartsData, ThrowOnError>
): RequestResult<ListDetachedPartsResponses, ListDetachedPartsErrors, ThrowOnError> =>
  (options.client ?? client).get<ListDetachedPartsResponses, ListDetachedPartsErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: zListDetachedPartsPath,
          query: z.optional(zListDetachedPartsQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListDetachedPartsResponse.parseAsync(data),
    url: '/tables/{database}/{table}/detached-parts',
    ...options,
  });

/**
 * List active operations
 *
 * Returns current ClickHouse work in flight that matters to movoor.
 */
export const listOperations = <ThrowOnError extends boolean = false>(
  options?: Options<ListOperationsData, ThrowOnError>
): RequestResult<ListOperationsResponses, ListOperationsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListOperationsResponses, ListOperationsErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(zListOperationsQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListOperationsResponse.parseAsync(data),
    url: '/operations',
    ...options,
  });

/**
 * List mutations
 *
 * Returns detailed unfinished and recent mutations from system.mutations, per node.
 */
export const listMutations = <ThrowOnError extends boolean = false>(
  options?: Options<ListMutationsData, ThrowOnError>
): RequestResult<ListMutationsResponses, ListMutationsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListMutationsResponses, ListMutationsErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(zListMutationsQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListMutationsResponse.parseAsync(data),
    url: '/operations/mutations',
    ...options,
  });

/**
 * List replication queue items
 *
 * Returns raw replication queue evidence from system.replication_queue, per node.
 */
export const listReplicationQueue = <ThrowOnError extends boolean = false>(
  options?: Options<ListReplicationQueueData, ThrowOnError>
): RequestResult<ListReplicationQueueResponses, ListReplicationQueueErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListReplicationQueueResponses, ListReplicationQueueErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(zListReplicationQueueQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListReplicationQueueResponse.parseAsync(data),
    url: '/operations/replication-queue',
    ...options,
  });

/**
 * List recent part events
 *
 * Returns recent part history from system.part_log when enabled. The
 * scan is bounded to the requested from/to window (defaulting to the
 * last 7 days) and to the newest 1000 events per table per node. If a
 * node is reachable but part_log is unavailable, return partial data
 * with a capability warning.
 *
 */
export const listPartEvents = <ThrowOnError extends boolean = false>(
  options?: Options<ListPartEventsData, ThrowOnError>
): RequestResult<ListPartEventsResponses, ListPartEventsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListPartEventsResponses, ListPartEventsErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(zListPartEventsQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListPartEventsResponse.parseAsync(data),
    url: '/part-events',
    ...options,
  });

/**
 * List conditions
 *
 * Returns a flattened, unpaginated triage list. The list can grow with the
 * observed cluster state, but the intended UI workload is bounded by the
 * configured tables and nodes.
 *
 */
export const listConditions = <ThrowOnError extends boolean = false>(
  options?: Options<ListConditionsData, ThrowOnError>
): RequestResult<ListConditionsResponses, ListConditionsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListConditionsResponses, ListConditionsErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(zListConditionsQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zListConditionsResponse.parseAsync(data),
    url: '/conditions',
    ...options,
  });

/**
 * Get tiering plan
 *
 * Returns the controller's cached per-node table snapshots. Unlike the
 * cluster explorer endpoints, this endpoint does not query ClickHouse on
 * demand; every table carries the reconcile timestamp, generation, and
 * any last observation error for that cached plan.
 *
 */
export const getTieringPlan = <ThrowOnError extends boolean = false>(
  options?: Options<GetTieringPlanData, ThrowOnError>
): RequestResult<GetTieringPlanResponses, GetTieringPlanErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetTieringPlanResponses, GetTieringPlanErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(zGetTieringPlanQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zGetTieringPlanResponse.parseAsync(data),
    url: '/tiering/plan',
    ...options,
  });

/**
 * Get tiering controller status
 *
 * Returns runtime dispatch state, rate limits, and in-flight tiering legs.
 */
export const getTieringStatus = <ThrowOnError extends boolean = false>(
  options?: Options<GetTieringStatusData, ThrowOnError>
): RequestResult<GetTieringStatusResponses, GetTieringStatusErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetTieringStatusResponses, GetTieringStatusErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(z.never()),
        })
        .parseAsync(data),
    responseValidator: async data => await zGetTieringStatusResponse.parseAsync(data),
    url: '/tiering/status',
    ...options,
  });

/**
 * List tiering action history
 *
 * Returns the in-memory action ring buffer. Structured logs are the durable history.
 */
export const getTieringHistory = <ThrowOnError extends boolean = false>(
  options?: Options<GetTieringHistoryData, ThrowOnError>
): RequestResult<GetTieringHistoryResponses, GetTieringHistoryErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetTieringHistoryResponses, GetTieringHistoryErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(zGetTieringHistoryQuery),
        })
        .parseAsync(data),
    responseValidator: async data => await zGetTieringHistoryResponse.parseAsync(data),
    url: '/tiering/history',
    ...options,
  });

/**
 * Pause tiering dispatch
 *
 * Stops dispatching new tiering actions. Existing in-flight work is allowed to drain.
 */
export const pauseTiering = <ThrowOnError extends boolean = false>(
  options?: Options<PauseTieringData, ThrowOnError>
): RequestResult<PauseTieringResponses, PauseTieringErrors, ThrowOnError> =>
  (options?.client ?? client).post<PauseTieringResponses, PauseTieringErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(z.never()),
        })
        .parseAsync(data),
    responseValidator: async data => await zPauseTieringResponse.parseAsync(data),
    url: '/tiering/pause',
    ...options,
  });

/**
 * Resume tiering dispatch
 *
 * Allows the controller to dispatch new tiering actions again.
 */
export const resumeTiering = <ThrowOnError extends boolean = false>(
  options?: Options<ResumeTieringData, ThrowOnError>
): RequestResult<ResumeTieringResponses, ResumeTieringErrors, ThrowOnError> =>
  (options?.client ?? client).post<ResumeTieringResponses, ResumeTieringErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: z.optional(z.never()),
          path: z.optional(z.never()),
          query: z.optional(z.never()),
        })
        .parseAsync(data),
    responseValidator: async data => await zResumeTieringResponse.parseAsync(data),
    url: '/tiering/resume',
    ...options,
  });

/**
 * Apply one tiering decision
 *
 * Runs one supervised executor attempt for the partition's current
 * actionable verdict. The request must include nodeId and the stateToken
 * observed from /tiering/plan; stale tokens return 409.
 *
 */
export const applyTieringPartition = <ThrowOnError extends boolean = false>(
  options: Options<ApplyTieringPartitionData, ThrowOnError>
): RequestResult<ApplyTieringPartitionResponses, ApplyTieringPartitionErrors, ThrowOnError> =>
  (options.client ?? client).post<ApplyTieringPartitionResponses, ApplyTieringPartitionErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: zApplyTieringPartitionBody,
          path: zApplyTieringPartitionPath,
          query: zApplyTieringPartitionQuery,
        })
        .parseAsync(data),
    responseValidator: async data => await zApplyTieringPartitionResponse.parseAsync(data),
    url: '/tiering/tables/{database}/{table}/partitions/{partitionId}/apply',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Retry one stalled tiering partition
 *
 * Re-runs one supervised executor attempt for a stalled partition. The
 * request must include nodeId and the current stateToken from
 * /tiering/plan; stale tokens return 409.
 *
 */
export const retryTieringPartition = <ThrowOnError extends boolean = false>(
  options: Options<RetryTieringPartitionData, ThrowOnError>
): RequestResult<RetryTieringPartitionResponses, RetryTieringPartitionErrors, ThrowOnError> =>
  (options.client ?? client).post<RetryTieringPartitionResponses, RetryTieringPartitionErrors, ThrowOnError>({
    requestValidator: async data =>
      await z
        .object({
          body: zRetryTieringPartitionBody,
          path: zRetryTieringPartitionPath,
          query: zRetryTieringPartitionQuery,
        })
        .parseAsync(data),
    responseValidator: async data => await zRetryTieringPartitionResponse.parseAsync(data),
    url: '/tiering/tables/{database}/{table}/partitions/{partitionId}/retry',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
