// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/mini';

/**
 * Exact unsigned 64-bit ClickHouse integer encoded as decimal text.
 */
export const zUInt64String = z.string().check(z.regex(/^[0-9]+$/));

/**
 * Exact signed ClickHouse integer encoded as decimal text.
 */
export const zInt64String = z.string().check(z.regex(/^-?[0-9]+$/));

/**
 * Nullable exact unsigned 64-bit ClickHouse integer.
 */
export const zNullableUInt64String = z.nullable(zUInt64String);

/**
 * Nullable RFC3339 timestamp.
 */
export const zNullableDateTime = z.nullable(z.iso.datetime());

/**
 * Nullable string.
 */
export const zNullableString = z.nullable(z.string());

export const zHealth = z.object({
  status: z.string(),
});

export const zProblemError = z.object({
  parameter: z.optional(z.string()),
  detail: z.string(),
});

/**
 * RFC 9457 problem details response.
 */
export const zProblemDetails = z.object({
  type: z.url(),
  title: z.string(),
  status: z.int().check(z.gte(400), z.lte(599)),
  detail: z.string(),
  instance: z.optional(z.string()),
  errors: z.optional(z.array(zProblemError)),
});

/**
 * API-owned condition severity.
 */
export const zSeverity = z.enum(['critical', 'warning', 'info']);

/**
 * API-owned collection warning category.
 */
export const zWarningKind = z.enum(['reachability', 'capability', 'partial_data', 'query_error']);

/**
 * API-owned placement relative to the table's configured targetDisk. This
 * is not a hot/cold tier vocabulary.
 *
 */
export const zPlacement = z.enum([
  'on_target',
  'off_target',
  'split',
  'replica_divergent',
  'missing_replica',
  'unknown',
]);

/**
 * API-owned operation kind.
 */
export const zOperationKind = z.enum(['move', 'merge', 'mutation', 'fetch', 'replication_queue']);

/**
 * Tiering execution mode.
 */
export const zTieringMode = z.enum(['off', 'plan', 'enforce']);

/**
 * Derived physical tiering status.
 */
export const zTieringPartitionStatus = z.enum(['hot', 'ready', 'tiered', 'split', 'stalled', 'misconfigured']);

/**
 * Derived action the controller would issue for this partition. Each
 * actionable decision is a single convergence leg; multi-step flows
 * (e.g. the remerge strategy's consolidate, optimize, tier sequence)
 * chain through re-classification across reconcile cycles. The
 * consolidate leg co-locates a split partition's parts on the table's
 * optimizeOn side before the merge.
 *
 */
export const zTieringDecision = z.enum(['none', 'keep', 'hold', 'consolidate', 'optimize', 'tier', 'append']);

/**
 * Runtime dispatch state.
 */
export const zTieringPauseState = z.enum(['running', 'stopping', 'stopped']);

export const zTieringAgeBasis = z.enum(['partitionTime', 'frontier']);

export const zTieringResplitStrategy = z.enum(['auto', 'remerge', 'append', 'hold']);

/**
 * Where the optimize leg runs. This also decides which direction a split
 * partition's parts move to co-locate before the merge: hot pulls cold
 * strays back for the round-trip; cold appends hot strays and merges in
 * place. Cold-side merges are intended only for target disks where FINAL
 * merges are operationally acceptable.
 *
 */
export const zTieringOptimizeSide = z.enum(['hot', 'cold']);

/**
 * Request-time collection warning. kind=reachability with a nodeId must
 * correspond to a /nodes item with reachable=false. Other warning kinds do
 * not imply node reachability failure.
 *
 */
export const zCollectionWarning = z.object({
  kind: zWarningKind,
  code: z.string(),
  message: z.string(),
  nodeId: z.optional(z.string()),
});

/**
 * Request-time collection metadata. counts in responses describe the full
 * matched result set across collected nodes. A 200 response can be partial
 * when at least one node responded; zero responding nodes returns 503.
 *
 */
export const zCollectionMeta = z.object({
  collectedAt: z.iso.datetime(),
  partial: z.boolean(),
  collectionDurationMs: z.int().check(z.gte(0)),
  nodesExpected: z.int().check(z.gte(0)),
  nodesResponded: z.int().check(z.gte(0)),
  nodesFailed: z.int().check(z.gte(0)),
  warnings: z.array(zCollectionWarning),
});

export const zNodeRef = z.object({
  nodeId: z.string(),
  shard: z.string(),
  replica: z.string(),
});

/**
 * Ready-to-use uri-reference links, usually absolute-from-host paths like
 * /api/v1/tables/.... Clients should not resolve these against servers.url.
 * Links are included only when they encode useful filters or joins.
 *
 */
export const zLinkMap = z.record(z.string(), z.string());

/**
 * Opaque structured evidence for the operator UI.
 */
export const zEvidence = z.record(z.string(), z.unknown());

/**
 * Condition embedded in a specific resource.
 */
export const zEmbeddedCondition = z.object({
  code: z.string(),
  severity: zSeverity,
  message: z.optional(z.string()),
  count: z.optional(z.int().check(z.gte(0))),
  evidence: z.optional(zEvidence),
});

/**
 * Fixed, zero-filled counts keyed by API-owned condition severity.
 */
export const zSeverityCounts = z.object({
  critical: z.int().check(z.gte(0)),
  warning: z.int().check(z.gte(0)),
  info: z.int().check(z.gte(0)),
});

/**
 * Fixed, zero-filled counts keyed by API-owned placement.
 */
export const zPlacementCounts = z.object({
  on_target: z.int().check(z.gte(0)),
  off_target: z.int().check(z.gte(0)),
  split: z.int().check(z.gte(0)),
  replica_divergent: z.int().check(z.gte(0)),
  missing_replica: z.int().check(z.gte(0)),
  unknown: z.int().check(z.gte(0)),
});

/**
 * Fixed, zero-filled counts keyed by known partition operation overlays.
 */
export const zPartitionOperationCounts = z.object({
  moving: z.int().check(z.gte(0)),
  merging: z.int().check(z.gte(0)),
  mutating: z.int().check(z.gte(0)),
  fetching: z.int().check(z.gte(0)),
});

/**
 * Fixed, zero-filled counts keyed by API-owned operation kind.
 */
export const zOperationKindCounts = z.object({
  move: z.int().check(z.gte(0)),
  merge: z.int().check(z.gte(0)),
  mutation: z.int().check(z.gte(0)),
  fetch: z.int().check(z.gte(0)),
  replication_queue: z.int().check(z.gte(0)),
});

/**
 * Observed-key counts for open vocabularies.
 */
export const zOpenCountMap = z.record(z.string(), z.int().check(z.gte(0)));

export const zReplicationSummary = z.object({
  queueSize: z.optional(zUInt64String),
  absoluteDelaySeconds: z.optional(zUInt64String),
  futureParts: z.optional(zUInt64String),
  totalReplicas: z.optional(zUInt64String),
  activeReplicas: z.optional(zUInt64String),
});

export const zBackgroundPools = z.object({
  mergesAndMutations: z.optional(zUInt64String),
  moves: z.optional(zUInt64String),
  fetches: z.optional(zUInt64String),
});

export const zNode = z.intersection(
  zNodeRef,
  z.object({
    endpoint: z.url(),
    reachable: z.boolean(),
    observedAt: z.iso.datetime(),
    version: z.optional(z.string()),
    timezone: z.optional(z.string()),
    uptimeSeconds: z.optional(zUInt64String),
    readonly: z.optional(z.boolean()),
    sessionExpired: z.optional(z.boolean()),
    replication: z.optional(zReplicationSummary),
    backgroundPools: z.optional(zBackgroundPools),
    lastError: zNullableString,
  })
);

export const zNodesResponse = z.object({
  collection: zCollectionMeta,
  items: z.array(zNode),
});

export const zStorageDisk = z.intersection(
  zNodeRef,
  z.object({
    disk: z.string(),
    type: z.string(),
    objectStorageType: z.string(),
    isRemote: z.boolean(),
    isBroken: z.boolean(),
    path: z.optional(zNullableString),
    cachePath: z.optional(zNullableString),
    capacityKnown: z.boolean(),
    freeSpaceBytes: zNullableUInt64String,
    totalSpaceBytes: zNullableUInt64String,
    unreservedSpaceBytes: zNullableUInt64String,
    usedByActivePartsBytes: zUInt64String,
  })
);

export const zStorageDisksResponse = z.object({
  collection: zCollectionMeta,
  items: z.array(zStorageDisk),
});

export const zTableBase = z.object({
  database: z.string(),
  table: z.string(),
  engine: z.string(),
  storagePolicy: z.string(),
  targetDisk: z.string(),
  partitionKey: z.string(),
  sortingKey: z.string(),
  primaryKey: z.string(),
  versionColumn: z.nullish(z.string()),
});

export const zTableListItem = z.intersection(
  zTableBase,
  z.object({
    nodesObserved: z.int().check(z.gte(0)),
    shardsObserved: z.int().check(z.gte(0)),
    replicasPerShard: z.int().check(z.gte(0)),
    activePartitions: z.int().check(z.gte(0)),
    activeParts: zUInt64String,
    rows: zUInt64String,
    bytesOnDisk: zUInt64String,
    partitionPlacements: zPlacementCounts,
    partitionOperations: zPartitionOperationCounts,
    activeOperations: z.int().check(z.gte(0)),
    conditions: z.array(zEmbeddedCondition),
    links: zLinkMap,
  })
);

export const zTablesResponse = z.object({
  collection: zCollectionMeta,
  items: z.array(zTableListItem),
});

export const zReplicaState = z.object({
  readonly: z.optional(z.boolean()),
  sessionExpired: z.optional(z.boolean()),
  queueSize: z.optional(zUInt64String),
  absoluteDelaySeconds: z.optional(zUInt64String),
  totalReplicas: z.optional(zUInt64String),
  activeReplicas: z.optional(zUInt64String),
});

export const zNodeTableState = z.object({
  nodeId: z.string(),
  engine: z.string(),
  activeParts: zUInt64String,
  rows: zUInt64String,
  bytesOnDisk: zUInt64String,
  replica: z.optional(zReplicaState),
});

export const zTableDetail = z.intersection(
  zTableBase,
  z.object({
    uuid: z.string(),
    samplingKey: z.string(),
    isReplicated: z.boolean(),
    nodesObserved: z.int().check(z.gte(0)),
    activePartitions: z.int().check(z.gte(0)),
    activeParts: zUInt64String,
    rows: zUInt64String,
    bytesOnDisk: zUInt64String,
    minPartition: z.nullish(z.string()),
    maxPartition: z.nullish(z.string()),
    lastModificationTime: z.optional(zNullableDateTime),
    partitionPlacements: zPlacementCounts,
    partitionOperations: zPartitionOperationCounts,
    nodes: z.array(zNodeTableState),
    conditions: z.array(zEmbeddedCondition),
  })
);

export const zTableResponse = z.object({
  collection: zCollectionMeta,
  item: zTableDetail,
});

export const zTableColumn = z.object({
  name: z.string(),
  position: z.int().check(z.gte(1)),
  type: z.string(),
  kind: z.string(),
  defaultKind: zNullableString,
  defaultExpression: zNullableString,
  codecExpression: zNullableString,
  ttlExpression: zNullableString,
  comment: z.string(),
  isInPartitionKey: z.boolean(),
  isInSortingKey: z.boolean(),
  isInPrimaryKey: z.boolean(),
  isInSamplingKey: z.boolean(),
});

export const zNodeColumns = z.intersection(
  zNodeRef,
  z.object({
    columns: z.array(zTableColumn),
    conditions: z.array(zEmbeddedCondition),
  })
);

export const zTableColumnsResponse = z.object({
  collection: zCollectionMeta,
  database: z.string(),
  table: z.string(),
  items: z.array(zNodeColumns),
  conditions: z.array(zEmbeddedCondition),
});

export const zPartitionPlacement = z.intersection(
  zNodeRef,
  z.object({
    disk: z.string(),
    activeParts: zUInt64String,
    rows: zUInt64String,
    bytesOnDisk: zUInt64String,
    lastModificationTime: z.optional(zNullableDateTime),
  })
);

export const zPartition = z.object({
  database: z.string(),
  table: z.string(),
  partition: z.string(),
  partitionId: z.string(),
  targetDisk: z.string(),
  placement: zPlacement,
  operations: z.array(z.string()),
  disks: z.array(z.string()),
  activeParts: zUInt64String,
  rows: zUInt64String,
  bytesOnDisk: zUInt64String,
  lastModificationTime: z.optional(zNullableDateTime),
  placements: z.array(zPartitionPlacement),
  conditions: z.array(zEmbeddedCondition),
});

export const zTablePartitionsResponse = z.object({
  collection: zCollectionMeta,
  items: z.array(zPartition),
});

/**
 * Raw ClickHouse TTL info object.
 */
export const zTtlInfo = z.record(z.string(), z.unknown());

export const zTablePart = z.intersection(
  zNodeRef,
  z.object({
    database: z.string(),
    table: z.string(),
    partition: z.string(),
    partitionId: z.string(),
    partName: z.string(),
    uuid: z.optional(z.string()),
    active: z.boolean(),
    disk: z.string(),
    path: z.string(),
    partType: z.string(),
    rows: zUInt64String,
    marks: z.optional(zUInt64String),
    bytesOnDisk: zUInt64String,
    dataCompressedBytes: z.optional(zUInt64String),
    dataUncompressedBytes: z.optional(zUInt64String),
    marksBytes: z.optional(zUInt64String),
    primaryKeyBytesInMemory: z.optional(zUInt64String),
    primaryKeyBytesInMemoryAllocated: z.optional(zUInt64String),
    secondaryIndicesCompressedBytes: z.optional(zUInt64String),
    secondaryIndicesUncompressedBytes: z.optional(zUInt64String),
    secondaryIndicesMarksBytes: z.optional(zUInt64String),
    modificationTime: z.iso.datetime(),
    removeTime: z.optional(zNullableDateTime),
    refcount: z.optional(zUInt64String),
    minBlockNumber: z.optional(zInt64String),
    maxBlockNumber: z.optional(zInt64String),
    level: z.optional(zUInt64String),
    dataVersion: z.optional(zUInt64String),
    deleteTtlInfoMin: z.optional(zNullableDateTime),
    deleteTtlInfoMax: z.optional(zNullableDateTime),
    moveTtlInfo: z.optional(z.array(zTtlInfo)),
    recompressionTtlInfo: z.optional(z.array(zTtlInfo)),
    defaultCompressionCodec: z.optional(z.string()),
    conditions: z.array(zEmbeddedCondition),
  })
);

export const zTablePartsResponse = z.object({
  collection: zCollectionMeta,
  database: z.string(),
  table: z.string(),
  items: z.array(zTablePart),
});

export const zDetachedPart = z.intersection(
  zNodeRef,
  z.object({
    database: z.string(),
    table: z.string(),
    partitionId: z.string(),
    partName: z.string(),
    disk: z.string(),
    reason: z.string(),
    path: z.string(),
    bytesOnDisk: zUInt64String,
    rows: zUInt64String,
    minBlockNumber: z.optional(zInt64String),
    maxBlockNumber: z.optional(zInt64String),
    level: z.optional(zUInt64String),
    modificationTime: z.optional(z.iso.datetime()),
    conditions: z.array(zEmbeddedCondition),
  })
);

/**
 * Counts for the full matched detached part set.
 */
export const zDetachedPartCounts = z.object({
  total: z.int().check(z.gte(0)),
  byReason: zOpenCountMap,
});

export const zDetachedPartsResponse = z.object({
  collection: zCollectionMeta,
  database: z.string(),
  table: z.string(),
  items: z.array(zDetachedPart),
  counts: zDetachedPartCounts,
});

export const zOperation = z.object({
  operationId: z.string(),
  kind: zOperationKind,
  nodeId: z.string(),
  database: z.string(),
  table: z.string(),
  partition: z.optional(zNullableString),
  partitionId: z.optional(zNullableString),
  attemptId: z.string(),
  state: z.string(),
  elapsedSeconds: z.optional(z.number().check(z.gte(0))),
  progress: z.optional(z.number().check(z.gte(0), z.lte(1))),
  sourceDisk: z.optional(zNullableString),
  targetDisk: z.optional(zNullableString),
  bytesTotal: z.optional(zNullableUInt64String),
  bytesProcessed: z.optional(zNullableUInt64String),
  latestMessage: z.optional(zNullableString),
  startedAt: z.optional(zNullableDateTime),
});

/**
 * Counts for the full matched operation set.
 */
export const zOperationCounts = z.object({
  total: z.int().check(z.gte(0)),
  byKind: zOperationKindCounts,
});

export const zOperationsResponse = z.object({
  collection: zCollectionMeta,
  items: z.array(zOperation),
  counts: zOperationCounts,
});

export const zMutationBlockNumber = z.object({
  partitionId: z.string(),
  number: zUInt64String,
});

export const zMutationOperation = z.intersection(
  zNodeRef,
  z.object({
    operationId: z.string(),
    kind: z.literal('mutation'),
    database: z.string(),
    table: z.string(),
    mutationId: z.string(),
    attemptId: z.string(),
    command: z.string(),
    createTime: z.iso.datetime(),
    isDone: z.boolean(),
    isKilled: z.boolean(),
    partsToDo: zUInt64String,
    partsToDoNames: z.array(z.string()),
    blockNumbers: z.array(zMutationBlockNumber),
    latestFailedPart: z.optional(zNullableString),
    latestFailTime: z.optional(zNullableDateTime),
    latestFailReason: z.optional(zNullableString),
    conditions: z.array(zEmbeddedCondition),
  })
);

/**
 * Counts for the full matched mutation set.
 */
export const zMutationCounts = z.object({
  total: z.int().check(z.gte(0)),
  unfinished: z.int().check(z.gte(0)),
  failed: z.int().check(z.gte(0)),
});

export const zMutationsResponse = z.object({
  collection: zCollectionMeta,
  items: z.array(zMutationOperation),
  counts: zMutationCounts,
});

export const zReplicationQueueOperation = z.intersection(
  zNodeRef,
  z.object({
    operationId: z.string(),
    kind: z.literal('replication_queue'),
    database: z.string(),
    table: z.string(),
    replicaName: z.string(),
    position: zUInt64String,
    nodeName: z.string(),
    attemptId: z.string(),
    type: z.string(),
    createTime: z.iso.datetime(),
    requiredQuorum: z.optional(zUInt64String),
    sourceReplica: z.optional(zNullableString),
    newPartName: z.optional(zNullableString),
    partsToMerge: z.optional(z.array(z.string())),
    isDetach: z.optional(z.boolean()),
    isCurrentlyExecuting: z.boolean(),
    numTries: zUInt64String,
    lastAttemptTime: z.optional(zNullableDateTime),
    lastPostponeTime: z.optional(zNullableDateTime),
    numPostponed: z.optional(zUInt64String),
    postponeReason: z.optional(zNullableString),
    lastException: z.optional(zNullableString),
    conditions: z.array(zEmbeddedCondition),
  })
);

/**
 * Counts for the full matched replication queue set.
 */
export const zReplicationQueueCounts = z.object({
  total: z.int().check(z.gte(0)),
  currentlyExecuting: z.int().check(z.gte(0)),
  withException: z.int().check(z.gte(0)),
  byType: zOpenCountMap,
});

export const zReplicationQueueResponse = z.object({
  collection: zCollectionMeta,
  items: z.array(zReplicationQueueOperation),
  counts: zReplicationQueueCounts,
});

export const zPartEvent = z.intersection(
  zNodeRef,
  z.object({
    eventId: z.string(),
    database: z.string(),
    table: z.string(),
    partitionId: z.string(),
    partName: z.string(),
    eventType: z.string(),
    eventTime: z.iso.datetime(),
    durationMs: zUInt64String,
    rows: zUInt64String,
    bytesCompressed: zUInt64String,
    bytesUncompressed: zUInt64String,
    readRows: z.optional(zUInt64String),
    readBytes: z.optional(zUInt64String),
    mergedFrom: z.optional(z.array(z.string())),
    sourceDisk: z.optional(zNullableString),
    targetDisk: z.optional(zNullableString),
    error: zInt64String,
    exception: z.optional(zNullableString),
  })
);

/**
 * Counts for the full matched part event set.
 */
export const zPartEventCounts = z.object({
  total: z.int().check(z.gte(0)),
  byEventType: zOpenCountMap,
  withErrors: z.int().check(z.gte(0)),
});

export const zPartEventsResponse = z.object({
  collection: zCollectionMeta,
  items: z.array(zPartEvent),
  counts: zPartEventCounts,
});

/**
 * Structured explanation of a hold/keep verdict: which gate is holding
 * the partition, the clock it is waiting on, and — where computable —
 * when it releases. successor-activity releases at the dead-group
 * horizon unless a newer sibling receives inserts first; stalled holds
 * carry the retry schedule instead.
 *
 */
export const zTieringHoldDetail = z.object({
  gate: z.string(),
  window: z.optional(z.string()),
  lastInsertAt: z.optional(z.iso.datetime()),
  lastChangeAt: z.optional(z.iso.datetime()),
  releasesAt: z.optional(z.iso.datetime()),
  retryAt: z.optional(z.iso.datetime()),
  failures: z.optional(z.int()),
});

export const zTieringDiskPart = z.object({
  disk: z.string(),
  parts: zUInt64String,
});

export const zTieringPolicy = z.object({
  mode: zTieringMode,
  ageBasis: zTieringAgeBasis,
  olderThan: z.optional(z.string()),
  field: z.optional(z.string()),
  keepLast: z.optional(zUInt64String),
  quietFor: z.string(),
  tierFrozenAfter: z.string(),
  targetDisk: z.string(),
  hotVolume: z.optional(z.string()),
  optimizeToParts: zUInt64String,
  skipOptimize: z.boolean(),
  optimizeOn: zTieringOptimizeSide,
  optimizeSkipAboveBytes: zUInt64String,
  resplitStrategy: zTieringResplitStrategy,
  resplitQuietFor: z.string(),
  fragmentAbovePartCount: zUInt64String,
});

export const zTieringCondition = z.object({
  severity: zSeverity,
  code: z.string(),
  message: z.string(),
  observedAt: z.iso.datetime(),
  nodeId: z.optional(z.string()),
  database: z.optional(z.string()),
  table: z.optional(z.string()),
  partition: z.optional(z.string()),
  partitionId: z.optional(z.string()),
});

export const zTieringTablePlan = z.object({
  nodeId: z.string(),
  database: z.string(),
  table: z.string(),
  reconciledAt: z.iso.datetime(),
  tickDurationMs: z.int().check(z.gte(0)),
  generation: z.string(),
  lastError: zNullableString,
  partitions: z.int().check(z.gte(0)),
  actionable: z.int().check(z.gte(0)),
  conditions: z.array(zTieringCondition),
});

export const zTieringPartition = z.intersection(
  zNodeRef,
  z.object({
    database: z.string(),
    table: z.string(),
    partition: z.string(),
    partitionId: z.string(),
    status: zTieringPartitionStatus,
    decision: zTieringDecision,
    reason: z.string(),
    rows: zUInt64String,
    bytesOnDisk: zUInt64String,
    activeParts: zUInt64String,
    disks: z.array(zTieringDiskPart),
    targetDisk: z.string(),
    hotVolume: z.optional(z.string()),
    policy: zTieringPolicy,
    conditions: z.array(zTieringCondition),
    hold: z.optional(zTieringHoldDetail),
    stateToken: z.string(),
    reconciledAt: z.iso.datetime(),
    effectiveMode: zTieringMode,
  })
);

export const zTieringPlanResponse = z.object({
  tables: z.array(zTieringTablePlan),
  items: z.array(zTieringPartition),
});

export const zTieringInFlightLeg = z.object({
  nodeId: z.string(),
  database: z.string(),
  table: z.string(),
  partition: z.string(),
  partitionId: z.string(),
  action: zTieringDecision,
  bytes: zUInt64String,
  startedAt: z.iso.datetime(),
  source: z.enum(['dispatch', 'supervised']),
});

export const zTieringStatus = z.object({
  mode: zTieringMode,
  pauseState: zTieringPauseState,
  pauseReason: z.optional(z.string()),
  inFlight: z.array(zTieringInFlightLeg),
  maxConcurrentPartitions: z.int().check(z.gte(0)),
  maxMovesPerCycle: z.int().check(z.gte(0)),
  maxBytesInFlight: zUInt64String,
  bytesInFlight: zUInt64String,
  maxBytesPerDay: zUInt64String,
  bytesMovedToday: zUInt64String,
  updatedAt: z.iso.datetime(),
});

export const zTieringHistoryEntry = z.object({
  time: z.iso.datetime(),
  nodeId: z.string(),
  database: z.string(),
  table: z.string(),
  partition: z.string(),
  partitionId: z.string(),
  action: zTieringDecision,
  outcome: z.string(),
  durationMs: z.int().check(z.gte(0)),
  bytes: zUInt64String,
  error: z.optional(z.string()),
  attemptId: z.optional(z.string()),
});

export const zTieringHistoryResponse = z.object({
  items: z.array(zTieringHistoryEntry),
});

export const zTieringApplyRequest = z.object({
  stateToken: z.string(),
});

export const zTieringApplyResponse = z.object({
  item: zTieringHistoryEntry,
});

export const zCondition = z.object({
  conditionId: z.string(),
  severity: zSeverity,
  code: z.string(),
  message: z.string(),
  database: z.optional(zNullableString),
  table: z.optional(zNullableString),
  partition: z.optional(zNullableString),
  partitionId: z.optional(zNullableString),
  nodeId: z.optional(zNullableString),
  observedAt: z.iso.datetime(),
  evidence: z.optional(zEvidence),
  links: z.optional(zLinkMap),
});

/**
 * Counts for the full matched condition set.
 */
export const zConditionCounts = z.object({
  total: z.int().check(z.gte(0)),
  bySeverity: zSeverityCounts,
});

export const zConditionsResponse = z.object({
  collection: zCollectionMeta,
  items: z.array(zCondition),
  counts: zConditionCounts,
});

/**
 * Filter physical parts by active flag.
 */
export const zActiveQuery = z.boolean();

/**
 * Filter disks by broken state.
 */
export const zBrokenQuery = z.boolean();

/**
 * Filter by open condition code. Unknown values are valid and return an
 * empty result set when no matching condition exists.
 *
 */
export const zCodeQuery = z.string();

/**
 * Filter columns by ClickHouse column kind. Known values include ordinary,
 * materialized, alias, default, and ephemeral. This is an open string.
 *
 */
export const zColumnKindQuery = z.string();

/**
 * Filter replication queue items by execution state.
 */
export const zCurrentlyExecutingQuery = z.boolean();

/**
 * ClickHouse database name.
 */
export const zDatabasePath = z.string();

/**
 * Filter by ClickHouse database name.
 */
export const zDatabaseQuery = z.string();

/**
 * Filter by ClickHouse disk name.
 */
export const zDiskQuery = z.string();

/**
 * Filter by ClickHouse disk type. This is an open ClickHouse string.
 */
export const zDiskTypeQuery = z.string();

/**
 * Filter mutations by isDone.
 */
export const zDoneQuery = z.boolean();

/**
 * Filter tables by engine.
 */
export const zEngineQuery = z.string();

/**
 * Filter by open ClickHouse part_log event type. Known values include
 * NewPart, MergeParts, DownloadPart, RemovePart, and MovePart. Unknown
 * values are valid and return an empty result set when no event exists.
 *
 */
export const zEventTypeQuery = z.string();

/**
 * Filter mutations by whether they have a latest failure.
 */
export const zFailedQuery = z.boolean();

/**
 * Include events at or after this RFC3339 timestamp. When omitted, the
 * window defaults to the last 7 days.
 *
 */
export const zFromQuery = z.iso.datetime();

/**
 * Filter resources by whether movoor detected conditions.
 */
export const zHasConditionsQuery = z.boolean();

/**
 * Filter replication queue items by whether lastException is set.
 */
export const zHasExceptionQuery = z.boolean();

/**
 * Filter tables by whether they have active partitions.
 */
export const zHasPartitionsQuery = z.boolean();

/**
 * Maximum bytes_on_disk filter for physical parts.
 */
export const zMaxBytesOnDiskQuery = zUInt64String;

/**
 * Minimum bytes_on_disk filter for physical parts.
 */
export const zMinBytesOnDiskQuery = zUInt64String;

/**
 * Filter by ClickHouse mutation id.
 */
export const zMutationIdQuery = z.string();

/**
 * Filter by object name.
 */
export const zNameQuery = z.string();

/**
 * Filter by movoor configured node id.
 */
export const zNodeIdQuery = z.string();

/**
 * Movoor configured node id. Tiering actions are node-local.
 */
export const zNodeIdQueryRequired = z.string();

/**
 * Filter by API-owned operation kind. Invalid values return 400.
 */
export const zOperationKindQuery = zOperationKind;

/**
 * Filter partitions by open operation overlay. Known values include moving,
 * merging, mutating, and fetching. Unknown values are valid and return an
 * empty result set when no matching overlay exists.
 *
 */
export const zOperationOverlayQuery = z.string();

/**
 * Filter by ClickHouse part name.
 */
export const zPartNameQuery = z.string();

/**
 * Filter by ClickHouse partition_id verbatim. partitionId is URL-safe but
 * unique only within the selected database and table.
 *
 */
export const zPartitionIdQuery = z.string();

/**
 * ClickHouse partition_id verbatim.
 */
export const zPartitionIdPath = z.string();

/**
 * Filter partitions by API-owned target-disk placement. Invalid values return 400.
 */
export const zPlacementQuery = zPlacement;

/**
 * Filter by open ClickHouse replication queue type. Known values include
 * GET_PART, MERGE_PARTS, MUTATE_PART, and DROP_RANGE.
 *
 */
export const zQueueTypeQuery = z.string();

/**
 * Filter by open detached part reason.
 */
export const zReasonQuery = z.string();

/**
 * Filter by replica id.
 */
export const zReplicaQuery = z.string();

/**
 * Filter by API-owned condition severity. Invalid values return 400.
 */
export const zSeverityQuery = zSeverity;

/**
 * Filter by shard id.
 */
export const zShardQuery = z.string();

/**
 * Filter tables by ClickHouse storage policy.
 */
export const zStoragePolicyQuery = z.string();

/**
 * ClickHouse table name.
 */
export const zTablePath = z.string();

/**
 * Filter by ClickHouse table name.
 */
export const zTableQuery = z.string();

/**
 * Include events before or at this RFC3339 timestamp.
 */
export const zToQuery = z.iso.datetime();

/**
 * Filter tiering plan entries by derived decision.
 */
export const zTieringDecisionQuery = zTieringDecision;

/**
 * Filter tiering plan entries by observed status.
 */
export const zTieringStatusQuery = zTieringPartitionStatus;

/**
 * Service is healthy.
 */
export const zGetHealthResponse = zHealth;

export const zListNodesQuery = z.object({
  nodeId: z.optional(z.string()),
});

/**
 * Nodes collected from the configured node list.
 */
export const zListNodesResponse = zNodesResponse;

export const zListStorageDisksQuery = z.object({
  nodeId: z.optional(z.string()),
  disk: z.optional(z.string()),
  type: z.optional(z.string()),
  broken: z.optional(z.boolean()),
});

/**
 * Disk inventory.
 */
export const zListStorageDisksResponse = zStorageDisksResponse;

export const zListTablesQuery = z.object({
  database: z.optional(z.string()),
  table: z.optional(z.string()),
  engine: z.optional(z.string()),
  storagePolicy: z.optional(z.string()),
  hasPartitions: z.optional(z.boolean()),
  hasConditions: z.optional(z.boolean()),
});

/**
 * Watched table inventory.
 */
export const zListTablesResponse = zTablesResponse;

export const zGetTablePath = z.object({
  database: z.string(),
  table: z.string(),
});

/**
 * Table detail.
 */
export const zGetTableResponse = zTableResponse;

export const zListTableColumnsPath = z.object({
  database: z.string(),
  table: z.string(),
});

export const zListTableColumnsQuery = z.object({
  nodeId: z.optional(z.string()),
  kind: z.optional(z.string()),
  name: z.optional(z.string()),
});

/**
 * Column definitions by node.
 */
export const zListTableColumnsResponse = zTableColumnsResponse;

export const zListTablePartitionsPath = z.object({
  database: z.string(),
  table: z.string(),
});

export const zListTablePartitionsQuery = z.object({
  placement: z.optional(zPlacement),
  operation: z.optional(z.string()),
  disk: z.optional(z.string()),
  nodeId: z.optional(z.string()),
  shard: z.optional(z.string()),
  replica: z.optional(z.string()),
  partitionId: z.optional(z.string()),
  hasConditions: z.optional(z.boolean()),
});

/**
 * Partition placement state.
 */
export const zListTablePartitionsResponse = zTablePartitionsResponse;

export const zListTablePartsPath = z.object({
  database: z.string(),
  table: z.string(),
});

export const zListTablePartsQuery = z.object({
  nodeId: z.optional(z.string()),
  shard: z.optional(z.string()),
  replica: z.optional(z.string()),
  partitionId: z.optional(z.string()),
  partName: z.optional(z.string()),
  disk: z.optional(z.string()),
  active: z.optional(z.boolean()),
  minBytesOnDisk: z.optional(zUInt64String),
  maxBytesOnDisk: z.optional(zUInt64String),
});

/**
 * Active part inventory.
 */
export const zListTablePartsResponse = zTablePartsResponse;

export const zListDetachedPartsPath = z.object({
  database: z.string(),
  table: z.string(),
});

export const zListDetachedPartsQuery = z.object({
  nodeId: z.optional(z.string()),
  shard: z.optional(z.string()),
  replica: z.optional(z.string()),
  partitionId: z.optional(z.string()),
  partName: z.optional(z.string()),
  disk: z.optional(z.string()),
  reason: z.optional(z.string()),
});

/**
 * Detached part inventory.
 */
export const zListDetachedPartsResponse = zDetachedPartsResponse;

export const zListOperationsQuery = z.object({
  kind: z.optional(zOperationKind),
  nodeId: z.optional(z.string()),
  database: z.optional(z.string()),
  table: z.optional(z.string()),
  partitionId: z.optional(z.string()),
});

/**
 * Active operations.
 */
export const zListOperationsResponse = zOperationsResponse;

export const zListMutationsQuery = z.object({
  nodeId: z.optional(z.string()),
  database: z.optional(z.string()),
  table: z.optional(z.string()),
  mutationId: z.optional(z.string()),
  done: z.optional(z.boolean()),
  failed: z.optional(z.boolean()),
});

/**
 * Mutation details.
 */
export const zListMutationsResponse = zMutationsResponse;

export const zListReplicationQueueQuery = z.object({
  nodeId: z.optional(z.string()),
  database: z.optional(z.string()),
  table: z.optional(z.string()),
  type: z.optional(z.string()),
  currentlyExecuting: z.optional(z.boolean()),
  hasException: z.optional(z.boolean()),
});

/**
 * Replication queue details.
 */
export const zListReplicationQueueResponse = zReplicationQueueResponse;

export const zListPartEventsQuery = z.object({
  nodeId: z.optional(z.string()),
  database: z.optional(z.string()),
  table: z.optional(z.string()),
  partitionId: z.optional(z.string()),
  partName: z.optional(z.string()),
  eventType: z.optional(z.string()),
  from: z.optional(z.iso.datetime()),
  to: z.optional(z.iso.datetime()),
});

/**
 * Recent part events.
 */
export const zListPartEventsResponse = zPartEventsResponse;

export const zListConditionsQuery = z.object({
  severity: z.optional(zSeverity),
  code: z.optional(z.string()),
  nodeId: z.optional(z.string()),
  database: z.optional(z.string()),
  table: z.optional(z.string()),
  partitionId: z.optional(z.string()),
});

/**
 * Flattened conditions.
 */
export const zListConditionsResponse = zConditionsResponse;

export const zGetTieringPlanQuery = z.object({
  nodeId: z.optional(z.string()),
  database: z.optional(z.string()),
  table: z.optional(z.string()),
  status: z.optional(zTieringPartitionStatus),
  decision: z.optional(zTieringDecision),
});

/**
 * Cached tiering plan snapshot.
 */
export const zGetTieringPlanResponse = zTieringPlanResponse;

/**
 * Current tiering runtime status.
 */
export const zGetTieringStatusResponse = zTieringStatus;

export const zGetTieringHistoryQuery = z.object({
  nodeId: z.optional(z.string()),
  database: z.optional(z.string()),
  table: z.optional(z.string()),
  partitionId: z.optional(z.string()),
});

/**
 * Recent tiering action history.
 */
export const zGetTieringHistoryResponse = zTieringHistoryResponse;

/**
 * Pause accepted.
 */
export const zPauseTieringResponse = zTieringStatus;

/**
 * Resume accepted.
 */
export const zResumeTieringResponse = zTieringStatus;

export const zApplyTieringPartitionBody = zTieringApplyRequest;

export const zApplyTieringPartitionPath = z.object({
  database: z.string(),
  table: z.string(),
  partitionId: z.string(),
});

export const zApplyTieringPartitionQuery = z.object({
  nodeId: z.string(),
});

/**
 * Apply admitted; the leg runs in the background.
 */
export const zApplyTieringPartitionResponse = zTieringApplyResponse;

export const zRetryTieringPartitionBody = zTieringApplyRequest;

export const zRetryTieringPartitionPath = z.object({
  database: z.string(),
  table: z.string(),
  partitionId: z.string(),
});

export const zRetryTieringPartitionQuery = z.object({
  nodeId: z.string(),
});

/**
 * Retry admitted; the leg runs in the background.
 */
export const zRetryTieringPartitionResponse = zTieringApplyResponse;
