// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  applyTieringPartition,
  getHealth,
  getTable,
  getTieringHistory,
  getTieringPlan,
  getTieringStatus,
  listConditions,
  listDetachedParts,
  listMutations,
  listNodes,
  listOperations,
  listPartEvents,
  listReplicationQueue,
  listStorageDisks,
  listTableColumns,
  listTablePartitions,
  listTableParts,
  listTables,
  type Options,
  pauseTiering,
  resumeTiering,
  retryTieringPartition,
} from '../sdk.gen';
import type {
  ApplyTieringPartitionData,
  ApplyTieringPartitionError,
  ApplyTieringPartitionResponse,
  GetHealthData,
  GetHealthError,
  GetHealthResponse,
  GetTableData,
  GetTableError,
  GetTableResponse,
  GetTieringHistoryData,
  GetTieringHistoryError,
  GetTieringHistoryResponse,
  GetTieringPlanData,
  GetTieringPlanError,
  GetTieringPlanResponse,
  GetTieringStatusData,
  GetTieringStatusError,
  GetTieringStatusResponse,
  ListConditionsData,
  ListConditionsError,
  ListConditionsResponse,
  ListDetachedPartsData,
  ListDetachedPartsError,
  ListDetachedPartsResponse,
  ListMutationsData,
  ListMutationsError,
  ListMutationsResponse,
  ListNodesData,
  ListNodesError,
  ListNodesResponse,
  ListOperationsData,
  ListOperationsError,
  ListOperationsResponse,
  ListPartEventsData,
  ListPartEventsError,
  ListPartEventsResponse,
  ListReplicationQueueData,
  ListReplicationQueueError,
  ListReplicationQueueResponse,
  ListStorageDisksData,
  ListStorageDisksError,
  ListStorageDisksResponse,
  ListTableColumnsData,
  ListTableColumnsError,
  ListTableColumnsResponse,
  ListTablePartitionsData,
  ListTablePartitionsError,
  ListTablePartitionsResponse,
  ListTablePartsData,
  ListTablePartsError,
  ListTablePartsResponse,
  ListTablesData,
  ListTablesError,
  ListTablesResponse,
  PauseTieringData,
  PauseTieringError,
  PauseTieringResponse,
  ResumeTieringData,
  ResumeTieringError,
  ResumeTieringResponse,
  RetryTieringPartitionData,
  RetryTieringPartitionError,
  RetryTieringPartitionResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

/**
 * Liveness probe
 *
 * Returns the current service status.
 */
export const getHealthOptions = (options?: Options<GetHealthData>) =>
  queryOptions<GetHealthResponse, GetHealthError, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHealth({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHealthQueryKey(options),
  });

export const listNodesQueryKey = (options?: Options<ListNodesData>) => createQueryKey('listNodes', options);

/**
 * List configured nodes
 *
 * Returns configured ClickHouse nodes plus request-time reachability and
 * coarse replication health. This endpoint is intentionally unpaginated:
 * the collection is bounded by the configured node list.
 *
 */
export const listNodesOptions = (options?: Options<ListNodesData>) =>
  queryOptions<ListNodesResponse, ListNodesError, ListNodesResponse, ReturnType<typeof listNodesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listNodes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listNodesQueryKey(options),
  });

export const listStorageDisksQueryKey = (options?: Options<ListStorageDisksData>) =>
  createQueryKey('listStorageDisks', options);

/**
 * List disks
 *
 * Returns disk inventory across configured nodes. Unknown or unbounded
 * remote capacity is represented with capacityKnown=false and null capacity
 * fields rather than ClickHouse sentinel values.
 *
 */
export const listStorageDisksOptions = (options?: Options<ListStorageDisksData>) =>
  queryOptions<
    ListStorageDisksResponse,
    ListStorageDisksError,
    ListStorageDisksResponse,
    ReturnType<typeof listStorageDisksQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listStorageDisks({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listStorageDisksQueryKey(options),
  });

export const listTablesQueryKey = (options?: Options<ListTablesData>) => createQueryKey('listTables', options);

/**
 * List watched tables
 *
 * Returns table inventory normalized across configured nodes. Missing
 * database or table query filters produce an empty result set, not 404.
 *
 */
export const listTablesOptions = (options?: Options<ListTablesData>) =>
  queryOptions<ListTablesResponse, ListTablesError, ListTablesResponse, ReturnType<typeof listTablesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTables({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTablesQueryKey(options),
  });

export const getTableQueryKey = (options: Options<GetTableData>) => createQueryKey('getTable', options);

/**
 * Get table detail
 *
 * Returns detailed table state, including per-node table metadata.
 */
export const getTableOptions = (options: Options<GetTableData>) =>
  queryOptions<GetTableResponse, GetTableError, GetTableResponse, ReturnType<typeof getTableQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTable({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTableQueryKey(options),
  });

export const listTableColumnsQueryKey = (options: Options<ListTableColumnsData>) =>
  createQueryKey('listTableColumns', options);

/**
 * List table columns
 *
 * Returns schema detail per node because schema drift can occur during failed or partial DDL.
 */
export const listTableColumnsOptions = (options: Options<ListTableColumnsData>) =>
  queryOptions<
    ListTableColumnsResponse,
    ListTableColumnsError,
    ListTableColumnsResponse,
    ReturnType<typeof listTableColumnsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTableColumns({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTableColumnsQueryKey(options),
  });

export const listTablePartitionsQueryKey = (options: Options<ListTablePartitionsData>) =>
  createQueryKey('listTablePartitions', options);

/**
 * List table partitions
 *
 * Returns logical partition placement and active operation overlays. The
 * partitionId field is ClickHouse system.parts.partition_id verbatim and
 * is unique only within the database/table pair.
 *
 */
export const listTablePartitionsOptions = (options: Options<ListTablePartitionsData>) =>
  queryOptions<
    ListTablePartitionsResponse,
    ListTablePartitionsError,
    ListTablePartitionsResponse,
    ReturnType<typeof listTablePartitionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTablePartitions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTablePartitionsQueryKey(options),
  });

export const listTablePartsQueryKey = (options: Options<ListTablePartsData>) =>
  createQueryKey('listTableParts', options);

/**
 * List active parts
 *
 * Returns physical parts from system.parts, per node.
 */
export const listTablePartsOptions = (options: Options<ListTablePartsData>) =>
  queryOptions<
    ListTablePartsResponse,
    ListTablePartsError,
    ListTablePartsResponse,
    ReturnType<typeof listTablePartsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTableParts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTablePartsQueryKey(options),
  });

export const listDetachedPartsQueryKey = (options: Options<ListDetachedPartsData>) =>
  createQueryKey('listDetachedParts', options);

/**
 * List detached parts
 *
 * Returns detached parts from system.detached_parts, per node.
 */
export const listDetachedPartsOptions = (options: Options<ListDetachedPartsData>) =>
  queryOptions<
    ListDetachedPartsResponse,
    ListDetachedPartsError,
    ListDetachedPartsResponse,
    ReturnType<typeof listDetachedPartsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listDetachedParts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listDetachedPartsQueryKey(options),
  });

export const listOperationsQueryKey = (options?: Options<ListOperationsData>) =>
  createQueryKey('listOperations', options);

/**
 * List active operations
 *
 * Returns current ClickHouse work in flight that matters to movoor.
 */
export const listOperationsOptions = (options?: Options<ListOperationsData>) =>
  queryOptions<
    ListOperationsResponse,
    ListOperationsError,
    ListOperationsResponse,
    ReturnType<typeof listOperationsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listOperations({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listOperationsQueryKey(options),
  });

export const listMutationsQueryKey = (options?: Options<ListMutationsData>) => createQueryKey('listMutations', options);

/**
 * List mutations
 *
 * Returns detailed unfinished and recent mutations from system.mutations, per node.
 */
export const listMutationsOptions = (options?: Options<ListMutationsData>) =>
  queryOptions<
    ListMutationsResponse,
    ListMutationsError,
    ListMutationsResponse,
    ReturnType<typeof listMutationsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMutations({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listMutationsQueryKey(options),
  });

export const listReplicationQueueQueryKey = (options?: Options<ListReplicationQueueData>) =>
  createQueryKey('listReplicationQueue', options);

/**
 * List replication queue items
 *
 * Returns raw replication queue evidence from system.replication_queue, per node.
 */
export const listReplicationQueueOptions = (options?: Options<ListReplicationQueueData>) =>
  queryOptions<
    ListReplicationQueueResponse,
    ListReplicationQueueError,
    ListReplicationQueueResponse,
    ReturnType<typeof listReplicationQueueQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listReplicationQueue({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listReplicationQueueQueryKey(options),
  });

export const listPartEventsQueryKey = (options?: Options<ListPartEventsData>) =>
  createQueryKey('listPartEvents', options);

/**
 * List recent part events
 *
 * Returns recent part history from system.part_log when enabled. The
 * scan is bounded to the requested from/to window (defaulting to the
 * last 7 days) and to the newest 1000 events per table per node. If a
 * node is reachable but part_log is unavailable, return partial data
 * with a capability warning.
 *
 */
export const listPartEventsOptions = (options?: Options<ListPartEventsData>) =>
  queryOptions<
    ListPartEventsResponse,
    ListPartEventsError,
    ListPartEventsResponse,
    ReturnType<typeof listPartEventsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listPartEvents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listPartEventsQueryKey(options),
  });

export const listConditionsQueryKey = (options?: Options<ListConditionsData>) =>
  createQueryKey('listConditions', options);

/**
 * List conditions
 *
 * Returns a flattened, unpaginated triage list. The list can grow with the
 * observed cluster state, but the intended UI workload is bounded by the
 * configured tables and nodes.
 *
 */
export const listConditionsOptions = (options?: Options<ListConditionsData>) =>
  queryOptions<
    ListConditionsResponse,
    ListConditionsError,
    ListConditionsResponse,
    ReturnType<typeof listConditionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listConditions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listConditionsQueryKey(options),
  });

export const getTieringPlanQueryKey = (options?: Options<GetTieringPlanData>) =>
  createQueryKey('getTieringPlan', options);

/**
 * Get tiering plan
 *
 * Returns the controller's cached per-node table snapshots. Unlike the
 * cluster explorer endpoints, this endpoint does not query ClickHouse on
 * demand; every table carries the reconcile timestamp, generation, and
 * any last observation error for that cached plan.
 *
 */
export const getTieringPlanOptions = (options?: Options<GetTieringPlanData>) =>
  queryOptions<
    GetTieringPlanResponse,
    GetTieringPlanError,
    GetTieringPlanResponse,
    ReturnType<typeof getTieringPlanQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTieringPlan({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTieringPlanQueryKey(options),
  });

export const getTieringStatusQueryKey = (options?: Options<GetTieringStatusData>) =>
  createQueryKey('getTieringStatus', options);

/**
 * Get tiering controller status
 *
 * Returns runtime dispatch state, rate limits, and in-flight tiering legs.
 */
export const getTieringStatusOptions = (options?: Options<GetTieringStatusData>) =>
  queryOptions<
    GetTieringStatusResponse,
    GetTieringStatusError,
    GetTieringStatusResponse,
    ReturnType<typeof getTieringStatusQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTieringStatus({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTieringStatusQueryKey(options),
  });

export const getTieringHistoryQueryKey = (options?: Options<GetTieringHistoryData>) =>
  createQueryKey('getTieringHistory', options);

/**
 * List tiering action history
 *
 * Returns the in-memory action ring buffer. Structured logs are the durable history.
 */
export const getTieringHistoryOptions = (options?: Options<GetTieringHistoryData>) =>
  queryOptions<
    GetTieringHistoryResponse,
    GetTieringHistoryError,
    GetTieringHistoryResponse,
    ReturnType<typeof getTieringHistoryQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTieringHistory({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTieringHistoryQueryKey(options),
  });

/**
 * Pause tiering dispatch
 *
 * Stops dispatching new tiering actions. Existing in-flight work is allowed to drain.
 */
export const pauseTieringMutation = (
  options?: Partial<Options<PauseTieringData>>
): UseMutationOptions<PauseTieringResponse, PauseTieringError, Options<PauseTieringData>> => {
  const mutationOptions: UseMutationOptions<PauseTieringResponse, PauseTieringError, Options<PauseTieringData>> = {
    mutationFn: async fnOptions => {
      const { data } = await pauseTiering({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Resume tiering dispatch
 *
 * Allows the controller to dispatch new tiering actions again.
 */
export const resumeTieringMutation = (
  options?: Partial<Options<ResumeTieringData>>
): UseMutationOptions<ResumeTieringResponse, ResumeTieringError, Options<ResumeTieringData>> => {
  const mutationOptions: UseMutationOptions<ResumeTieringResponse, ResumeTieringError, Options<ResumeTieringData>> = {
    mutationFn: async fnOptions => {
      const { data } = await resumeTiering({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Apply one tiering decision
 *
 * Runs one supervised executor attempt for the partition's current
 * actionable verdict. The request must include nodeId and the stateToken
 * observed from /tiering/plan; stale tokens return 409.
 *
 */
export const applyTieringPartitionMutation = (
  options?: Partial<Options<ApplyTieringPartitionData>>
): UseMutationOptions<
  ApplyTieringPartitionResponse,
  ApplyTieringPartitionError,
  Options<ApplyTieringPartitionData>
> => {
  const mutationOptions: UseMutationOptions<
    ApplyTieringPartitionResponse,
    ApplyTieringPartitionError,
    Options<ApplyTieringPartitionData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await applyTieringPartition({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Retry one stalled tiering partition
 *
 * Re-runs one supervised executor attempt for a stalled partition. The
 * request must include nodeId and the current stateToken from
 * /tiering/plan; stale tokens return 409.
 *
 */
export const retryTieringPartitionMutation = (
  options?: Partial<Options<RetryTieringPartitionData>>
): UseMutationOptions<
  RetryTieringPartitionResponse,
  RetryTieringPartitionError,
  Options<RetryTieringPartitionData>
> => {
  const mutationOptions: UseMutationOptions<
    RetryTieringPartitionResponse,
    RetryTieringPartitionError,
    Options<RetryTieringPartitionData>
  > = {
    mutationFn: async fnOptions => {
      const { data } = await retryTieringPartition({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
