// Code generated by ogen, DO NOT EDIT.

package rest

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ApplyTieringPartition implements applyTieringPartition operation.
	//
	// Starts one supervised executor attempt for the partition's current
	// actionable verdict. The request must include nodeId and the stateToken
	// observed from /tiering/plan; stale tokens return 409. The leg runs
	// detached from the request: the 202 response acknowledges admission with
	// outcome "started", the leg is visible in /tiering/status inFlight until
	// it converges, and its completion lands in /tiering/history.
	//
	// POST /tiering/tables/{database}/{table}/partitions/{partitionId}/apply
	ApplyTieringPartition(ctx context.Context, req *TieringApplyRequest, params ApplyTieringPartitionParams) (ApplyTieringPartitionRes, error)
	// GetHealth implements getHealth operation.
	//
	// Returns the current service status.
	//
	// GET /healthz
	GetHealth(ctx context.Context) (GetHealthRes, error)
	// GetTable implements getTable operation.
	//
	// Returns detailed table state, including per-node table metadata.
	//
	// GET /tables/{database}/{table}
	GetTable(ctx context.Context, params GetTableParams) (GetTableRes, error)
	// GetTieringHistory implements getTieringHistory operation.
	//
	// Returns the in-memory action ring buffer. Structured logs are the durable history.
	//
	// GET /tiering/history
	GetTieringHistory(ctx context.Context, params GetTieringHistoryParams) (GetTieringHistoryRes, error)
	// GetTieringPlan implements getTieringPlan operation.
	//
	// Returns the controller's cached per-node table snapshots. Unlike the
	// cluster explorer endpoints, this endpoint does not query ClickHouse on
	// demand; every table carries the reconcile timestamp, generation, and
	// any last observation error for that cached plan.
	//
	// GET /tiering/plan
	GetTieringPlan(ctx context.Context, params GetTieringPlanParams) (GetTieringPlanRes, error)
	// GetTieringStatus implements getTieringStatus operation.
	//
	// Returns runtime dispatch state, rate limits, and in-flight tiering legs.
	//
	// GET /tiering/status
	GetTieringStatus(ctx context.Context) (GetTieringStatusRes, error)
	// ListConditions implements listConditions operation.
	//
	// Returns a flattened, unpaginated triage list. The list can grow with the
	// observed cluster state, but the intended UI workload is bounded by the
	// configured tables and nodes.
	//
	// GET /conditions
	ListConditions(ctx context.Context, params ListConditionsParams) (ListConditionsRes, error)
	// ListDetachedParts implements listDetachedParts operation.
	//
	// Returns detached parts from system.detached_parts, per node.
	//
	// GET /tables/{database}/{table}/detached-parts
	ListDetachedParts(ctx context.Context, params ListDetachedPartsParams) (ListDetachedPartsRes, error)
	// ListMutations implements listMutations operation.
	//
	// Returns detailed unfinished and recent mutations from system.mutations, per node.
	//
	// GET /operations/mutations
	ListMutations(ctx context.Context, params ListMutationsParams) (ListMutationsRes, error)
	// ListNodes implements listNodes operation.
	//
	// Returns configured ClickHouse nodes plus request-time reachability and
	// coarse replication health. This endpoint is intentionally unpaginated:
	// the collection is bounded by the configured node list.
	//
	// GET /nodes
	ListNodes(ctx context.Context, params ListNodesParams) (ListNodesRes, error)
	// ListOperations implements listOperations operation.
	//
	// Returns current ClickHouse work in flight that matters to movoor.
	//
	// GET /operations
	ListOperations(ctx context.Context, params ListOperationsParams) (ListOperationsRes, error)
	// ListPartEvents implements listPartEvents operation.
	//
	// Returns recent part history from system.part_log when enabled. The
	// scan is bounded to the requested from/to window (defaulting to the
	// last 7 days) and to the newest 1000 events per table per node. If a
	// node is reachable but part_log is unavailable, return partial data
	// with a capability warning.
	//
	// GET /part-events
	ListPartEvents(ctx context.Context, params ListPartEventsParams) (ListPartEventsRes, error)
	// ListReplicationQueue implements listReplicationQueue operation.
	//
	// Returns raw replication queue evidence from system.replication_queue, per node.
	//
	// GET /operations/replication-queue
	ListReplicationQueue(ctx context.Context, params ListReplicationQueueParams) (ListReplicationQueueRes, error)
	// ListStorageDisks implements listStorageDisks operation.
	//
	// Returns disk inventory across configured nodes. Unknown or unbounded
	// remote capacity is represented with capacityKnown=false and null capacity
	// fields rather than ClickHouse sentinel values.
	//
	// GET /storage/disks
	ListStorageDisks(ctx context.Context, params ListStorageDisksParams) (ListStorageDisksRes, error)
	// ListTableColumns implements listTableColumns operation.
	//
	// Returns schema detail per node because schema drift can occur during failed or partial DDL.
	//
	// GET /tables/{database}/{table}/columns
	ListTableColumns(ctx context.Context, params ListTableColumnsParams) (ListTableColumnsRes, error)
	// ListTablePartitions implements listTablePartitions operation.
	//
	// Returns logical partition placement and active operation overlays. The
	// partitionId field is ClickHouse system.parts.partition_id verbatim and
	// is unique only within the database/table pair.
	//
	// GET /tables/{database}/{table}/partitions
	ListTablePartitions(ctx context.Context, params ListTablePartitionsParams) (ListTablePartitionsRes, error)
	// ListTableParts implements listTableParts operation.
	//
	// Returns physical parts from system.parts, per node.
	//
	// GET /tables/{database}/{table}/parts
	ListTableParts(ctx context.Context, params ListTablePartsParams) (ListTablePartsRes, error)
	// ListTables implements listTables operation.
	//
	// Returns table inventory normalized across configured nodes. Missing
	// database or table query filters produce an empty result set, not 404.
	//
	// GET /tables
	ListTables(ctx context.Context, params ListTablesParams) (ListTablesRes, error)
	// PauseTiering implements pauseTiering operation.
	//
	// Stops dispatching new tiering actions. Existing in-flight work is allowed to drain.
	//
	// POST /tiering/pause
	PauseTiering(ctx context.Context) (PauseTieringRes, error)
	// ResumeTiering implements resumeTiering operation.
	//
	// Allows the controller to dispatch new tiering actions again.
	//
	// POST /tiering/resume
	ResumeTiering(ctx context.Context) (ResumeTieringRes, error)
	// RetryTieringPartition implements retryTieringPartition operation.
	//
	// Re-runs one supervised executor attempt for a stalled partition. The
	// request must include nodeId and the current stateToken from
	// /tiering/plan; stale tokens return 409. Like apply, the leg runs
	// detached from the request and the 202 acknowledges admission with
	// outcome "started".
	//
	// POST /tiering/tables/{database}/{table}/partitions/{partitionId}/retry
	RetryTieringPartition(ctx context.Context, req *TieringApplyRequest, params RetryTieringPartitionParams) (RetryTieringPartitionRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
