// Code generated by ogen, DO NOT EDIT.

package rest

// OperationName is the ogen operation name
type OperationName = string

const (
	ApplyTieringPartitionOperation OperationName = "ApplyTieringPartition"
	GetHealthOperation             OperationName = "GetHealth"
	GetTableOperation              OperationName = "GetTable"
	GetTieringHistoryOperation     OperationName = "GetTieringHistory"
	GetTieringPlanOperation        OperationName = "GetTieringPlan"
	GetTieringStatusOperation      OperationName = "GetTieringStatus"
	ListConditionsOperation        OperationName = "ListConditions"
	ListDetachedPartsOperation     OperationName = "ListDetachedParts"
	ListMutationsOperation         OperationName = "ListMutations"
	ListNodesOperation             OperationName = "ListNodes"
	ListOperationsOperation        OperationName = "ListOperations"
	ListPartEventsOperation        OperationName = "ListPartEvents"
	ListReplicationQueueOperation  OperationName = "ListReplicationQueue"
	ListStorageDisksOperation      OperationName = "ListStorageDisks"
	ListTableColumnsOperation      OperationName = "ListTableColumns"
	ListTablePartitionsOperation   OperationName = "ListTablePartitions"
	ListTablePartsOperation        OperationName = "ListTableParts"
	ListTablesOperation            OperationName = "ListTables"
	PauseTieringOperation          OperationName = "PauseTiering"
	ResumeTieringOperation         OperationName = "ResumeTiering"
	RetryTieringPartitionOperation OperationName = "RetryTieringPartition"
)
