// Code generated by ogen, DO NOT EDIT.
package rest

type ApplyTieringPartitionRes interface {
	applyTieringPartitionRes()
}

type GetHealthRes interface {
	getHealthRes()
}

type GetTableRes interface {
	getTableRes()
}

type GetTieringHistoryRes interface {
	getTieringHistoryRes()
}

type GetTieringPlanRes interface {
	getTieringPlanRes()
}

type GetTieringStatusRes interface {
	getTieringStatusRes()
}

type ListConditionsRes interface {
	listConditionsRes()
}

type ListDetachedPartsRes interface {
	listDetachedPartsRes()
}

type ListMutationsRes interface {
	listMutationsRes()
}

type ListNodesRes interface {
	listNodesRes()
}

type ListOperationsRes interface {
	listOperationsRes()
}

type ListPartEventsRes interface {
	listPartEventsRes()
}

type ListReplicationQueueRes interface {
	listReplicationQueueRes()
}

type ListStorageDisksRes interface {
	listStorageDisksRes()
}

type ListTableColumnsRes interface {
	listTableColumnsRes()
}

type ListTablePartitionsRes interface {
	listTablePartitionsRes()
}

type ListTablePartsRes interface {
	listTablePartsRes()
}

type ListTablesRes interface {
	listTablesRes()
}

type PauseTieringRes interface {
	pauseTieringRes()
}

type ResumeTieringRes interface {
	resumeTieringRes()
}

type RetryTieringPartitionRes interface {
	retryTieringPartitionRes()
}
