// Code generated by ogen, DO NOT EDIT.

package rest

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ApplyTieringPartition implements applyTieringPartition operation.
//
// Starts one supervised executor attempt for the partition's current
// actionable verdict. The request must include nodeId and the stateToken
// observed from /tiering/plan; stale tokens return 409. The leg runs
// detached from the request: the 202 response acknowledges admission with
// outcome "started", the leg is visible in /tiering/status inFlight until
// it converges, and its completion lands in /tiering/history.
//
// POST /tiering/tables/{database}/{table}/partitions/{partitionId}/apply
func (UnimplementedHandler) ApplyTieringPartition(ctx context.Context, req *TieringApplyRequest, params ApplyTieringPartitionParams) (r ApplyTieringPartitionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Returns the current service status.
//
// GET /healthz
func (UnimplementedHandler) GetHealth(ctx context.Context) (r GetHealthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTable implements getTable operation.
//
// Returns detailed table state, including per-node table metadata.
//
// GET /tables/{database}/{table}
func (UnimplementedHandler) GetTable(ctx context.Context, params GetTableParams) (r GetTableRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTieringHistory implements getTieringHistory operation.
//
// Returns the in-memory action ring buffer. Structured logs are the durable history.
//
// GET /tiering/history
func (UnimplementedHandler) GetTieringHistory(ctx context.Context, params GetTieringHistoryParams) (r GetTieringHistoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTieringPlan implements getTieringPlan operation.
//
// Returns the controller's cached per-node table snapshots. Unlike the
// cluster explorer endpoints, this endpoint does not query ClickHouse on
// demand; every table carries the reconcile timestamp, generation, and
// any last observation error for that cached plan.
//
// GET /tiering/plan
func (UnimplementedHandler) GetTieringPlan(ctx context.Context, params GetTieringPlanParams) (r GetTieringPlanRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTieringStatus implements getTieringStatus operation.
//
// Returns runtime dispatch state, rate limits, and in-flight tiering legs.
//
// GET /tiering/status
func (UnimplementedHandler) GetTieringStatus(ctx context.Context) (r GetTieringStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListConditions implements listConditions operation.
//
// Returns a flattened, unpaginated triage list. The list can grow with the
// observed cluster state, but the intended UI workload is bounded by the
// configured tables and nodes.
//
// GET /conditions
func (UnimplementedHandler) ListConditions(ctx context.Context, params ListConditionsParams) (r ListConditionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDetachedParts implements listDetachedParts operation.
//
// Returns detached parts from system.detached_parts, per node.
//
// GET /tables/{database}/{table}/detached-parts
func (UnimplementedHandler) ListDetachedParts(ctx context.Context, params ListDetachedPartsParams) (r ListDetachedPartsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMutations implements listMutations operation.
//
// Returns detailed unfinished and recent mutations from system.mutations, per node.
//
// GET /operations/mutations
func (UnimplementedHandler) ListMutations(ctx context.Context, params ListMutationsParams) (r ListMutationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListNodes implements listNodes operation.
//
// Returns configured ClickHouse nodes plus request-time reachability and
// coarse replication health. This endpoint is intentionally unpaginated:
// the collection is bounded by the configured node list.
//
// GET /nodes
func (UnimplementedHandler) ListNodes(ctx context.Context, params ListNodesParams) (r ListNodesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListOperations implements listOperations operation.
//
// Returns current ClickHouse work in flight that matters to movoor.
//
// GET /operations
func (UnimplementedHandler) ListOperations(ctx context.Context, params ListOperationsParams) (r ListOperationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPartEvents implements listPartEvents operation.
//
// Returns recent part history from system.part_log when enabled. The
// scan is bounded to the requested from/to window (defaulting to the
// last 7 days) and to the newest 1000 events per table per node. If a
// node is reachable but part_log is unavailable, return partial data
// with a capability warning.
//
// GET /part-events
func (UnimplementedHandler) ListPartEvents(ctx context.Context, params ListPartEventsParams) (r ListPartEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListReplicationQueue implements listReplicationQueue operation.
//
// Returns raw replication queue evidence from system.replication_queue, per node.
//
// GET /operations/replication-queue
func (UnimplementedHandler) ListReplicationQueue(ctx context.Context, params ListReplicationQueueParams) (r ListReplicationQueueRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListStorageDisks implements listStorageDisks operation.
//
// Returns disk inventory across configured nodes. Unknown or unbounded
// remote capacity is represented with capacityKnown=false and null capacity
// fields rather than ClickHouse sentinel values.
//
// GET /storage/disks
func (UnimplementedHandler) ListStorageDisks(ctx context.Context, params ListStorageDisksParams) (r ListStorageDisksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTableColumns implements listTableColumns operation.
//
// Returns schema detail per node because schema drift can occur during failed or partial DDL.
//
// GET /tables/{database}/{table}/columns
func (UnimplementedHandler) ListTableColumns(ctx context.Context, params ListTableColumnsParams) (r ListTableColumnsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTablePartitions implements listTablePartitions operation.
//
// Returns logical partition placement and active operation overlays. The
// partitionId field is ClickHouse system.parts.partition_id verbatim and
// is unique only within the database/table pair.
//
// GET /tables/{database}/{table}/partitions
func (UnimplementedHandler) ListTablePartitions(ctx context.Context, params ListTablePartitionsParams) (r ListTablePartitionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTableParts implements listTableParts operation.
//
// Returns physical parts from system.parts, per node.
//
// GET /tables/{database}/{table}/parts
func (UnimplementedHandler) ListTableParts(ctx context.Context, params ListTablePartsParams) (r ListTablePartsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTables implements listTables operation.
//
// Returns table inventory normalized across configured nodes. Missing
// database or table query filters produce an empty result set, not 404.
//
// GET /tables
func (UnimplementedHandler) ListTables(ctx context.Context, params ListTablesParams) (r ListTablesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PauseTiering implements pauseTiering operation.
//
// Stops dispatching new tiering actions. Existing in-flight work is allowed to drain.
//
// POST /tiering/pause
func (UnimplementedHandler) PauseTiering(ctx context.Context) (r PauseTieringRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResumeTiering implements resumeTiering operation.
//
// Allows the controller to dispatch new tiering actions again.
//
// POST /tiering/resume
func (UnimplementedHandler) ResumeTiering(ctx context.Context) (r ResumeTieringRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RetryTieringPartition implements retryTieringPartition operation.
//
// Re-runs one supervised executor attempt for a stalled partition. The
// request must include nodeId and the current stateToken from
// /tiering/plan; stale tokens return 409. Like apply, the leg runs
// detached from the request and the 202 acknowledges admission with
// outcome "started".
//
// POST /tiering/tables/{database}/{table}/partitions/{partitionId}/retry
func (UnimplementedHandler) RetryTieringPartition(ctx context.Context, req *TieringApplyRequest, params RetryTieringPartitionParams) (r RetryTieringPartitionRes, _ error) {
	return r, ht.ErrNotImplemented
}
